name: Laravel CI process

on:
  push:
    branches: [main]
#koraci
jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

    #dodavanje php-a
      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, dom, fileinfo, sqlite3, pdo_sqlite
          coverage: none

    #dodavanje composera i laravela
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

    #dodavanje npm paketa
      - name: Install npm dependencies
        run: npm install

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

    #dodavanje build-a za produkciju
      - name: Build Vite assets
        run: npm run build

    #provjera laravel verzije
      - name: Verify Laravel application
        run: php artisan -V

    #ciscenje laravel cahe-a
     # - name: Clear Laravel optimized cache
     #   run: php artisan optimize:clear
    
    #popis ruta
      - name: Popis ruta
        run: php artisan route:list
